spring:
  config:
    import: optional:configserver:http://localhost:9999
  application:
    name: product-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
