spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http//localhost:9098/realms/micro-service"
  config:
    import: optional:configserver:http://localhost:9999
  application:
    name: gateway-service




