version: '3.8'

services:
  mysql:
    container_name: ms_mysql
    image: mysql:latest
    init: true
    environment:
      MYSQL_ROOT_PASSWORD: morris
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: morris
      MYSQL_PASSWORD: morris
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - microservices-net
    restart: unless-stopped

  phpmyadmin:
    container_name: ms_phpmyadmin
    image: phpmyadmin/phpmyadmin
    init: true
    environment:
      PMA_HOST: mysql
      PMA_USER: morris
      PMA_PASSWORD: morris
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    init: true
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: morris
      MONGO_INITDB_ROOT_PASSWORD: morris
    networks:
      - microservices-net
    restart: unless-stopped

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    init: true
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: morris
      ME_CONFIG_MONGODB_ADMINPASSWORD: morris
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    init: true
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP port
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
